- name: Copy the rsyslog conf 
  template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/roboshop.conf

- name: restart rsyslog
  systemd:
    name: syslog
    state: restarted

- name: Copy the elastic beats repo
  template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  yum:
    name: filebeat
    state: installed

- name: Copy Filebeat configuration
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes